#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 262686-web-01 35.153.93.135:80 check\n\tserver 262686-web-02 54.164.125.110:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
