#!/usr/bin/env bash
# Get the current date in the required format (day-month-year)
date_format=$(date +'%d-%m-%Y')

# Name of the dump file
dump_file="backup.sql"

# Compressed archive name
archive_name="$date_format.tar.gz"

# MySQL dump command
sudo mysqldump -u root -p"$1" --all-databases > "$dump_file"

# Create a tar.gz archive
tar -czvf "$archive_name" "$dump_file"
